### ISSUE TITLE
Does not reflash

### ISSUE THREAD

**Issue by karabas2011** [darkspr1te/mkstft35_bl_vet_fsmc#1]
Ok, now it boots without SDcard successfully.
But it does not flash new mkstft35.bin encrypted or nonencrypted.
I prefer nonencrypted because IAR builds it.

**Comment by darkspr1te** [comment]
do you get any output on the serial port? (wifi connector txd,rxd ) it will  report any errors there , lcd text support is coming.

**Comment by karabas2011** [comment]
I did not check yet. Now it simply loads already flashed firmware and ignores sdcard.
Maybe it thinks that there is no any sdcard inserted?

**Comment by karabas2011** [comment]
SD CARD not detected 1

working with un-encrypted mks firmware_run
Stack Address 800c000
Jump Address 800c004
Stack Address Value 20016dc0
Jump Address Value 805c805
                          SD CARD detected 0
FAT FS Link Driver OK
exit



Booting
Software version: 0.1
Board Build: "MKSTFT3.5-V1"
Loader Variant: iz3man loader
about to setup sd-card
MAIN: FatFs Init Failed Code: 3
Flash success

Boot application

**Comment by darkspr1te** [comment]
i can see from the log it's not seeing the sdcard, can you format it and try again, we have tested on another unit and it's flashing ok, my unit has not arrived yet so am relying on others for feedback

**Comment by karabas2011** [comment]
SD CARD detected 0 - what does it mean?
I think problems with my card reader
I resoldered it yesterday

**Comment by karabas2011** [comment]
I have resoldered cardreader. Now it works perfectly!
I am able to reflash my firmware!

As I think for encoded firmwares we need reflash bootloader  compiled with "#define Decrypt"?

**Comment by darkspr1te** [comment]
in platformio.ini there is -DDECRYPT or in Makefile -DDECRYPT to enable decrypt of mks official files. It's not fully working yet but will be soon so is disabled by default

**Comment by karabas2011** [comment]
Ok, I hope I will not need it
